### ISSUE TITLE
Внешний вызов dialogs.yandex.net (с прокси)

### ISSUE THREAD

**Issue by mazahakq** [skysilver-lab/majordomo-yandexhome#5]
При внешнем вызове dialogs.yandex.net не используется указанная в majordomo - USE_PROXY, что приводит к зависанию сервера от частых запросов при отсутствии интернета.

В блоке кода majordomo-yandexhome/modules/yandexhome/yandexhome.class.php (PropertySetHandle), после:
`
$url = "https://dialogs.yandex.net/api/v1/skills/".$this->config['CLIENT_KEY']."/callback/state";
`
https://github.com/skysilver-lab/majordomo-yandexhome/blob/6e0dd066da0259d666824ad9869466575ec1c86a/modules/yandexhome/yandexhome.class.php#L687

Как вариант предлагает добавить:
`
			if (defined('USE_PROXY') && USE_PROXY != '') {
				curl_setopt($crl, CURLOPT_PROXY, USE_PROXY);
				if (defined('USE_PROXY_AUTH') && USE_PROXY_AUTH != '') {
					curl_setopt($crl, CURLOPT_PROXYUSERPWD, USE_PROXY_AUTH);
				}
			}
`
Что решает проблему в этой части кода

**Comment by mazahakq** [comment]
https://github.com/skysilver-lab/majordomo-yandexhome/pull/7

**Comment by skysilver-lab** [comment]
Привет. Смержил PR.
